name: "NPM Publish Action"
description: "This action will deploy your package to NPM Custom Registry"
author: "GitHub"
inputs:
  debug:
    description: "npm debug level"
    default: "-ddd"
  username:
    description: "NPM username"
    required: true
  password:
    description: "NPM password"
    required: true
  email:
    description: "NPM email"
    required: true
  registry:
    description: "NPM registry"
    required: true
  package:
    description: "Package path"
    default: ""
runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      shell: docker build -t npm-publish --build-arg IGNORE_THIS={0} ${{ github.action_path }}
      run: ""
    - name: Publish to NPM
      shell: docker run --rm -v ${{ github.workspace }}/${{ inputs.package }}:/package npm-publish ${{ inputs.debug }} ${{ inputs.username }} ${{ inputs.password }} ${{ inputs.email }} ${{ inputs.registry }} {0}
      run: ""
